### PR TITLE
MM-19543 Force provided names to lowercase for standardization

### PR DESCRIPTION
**Pull request by gigawhitlocks**
A small change to force names to lowercase as part of input validation in all of the cloud plugin entrypoints that take a name.

Resolves MM-19543

### CODE REVIEW

**Comment by gigawhitlocks** [comment]
Yeah you know, I was thinking about doing this or even making Name a type so that there's an initialization step that's obviously necessary for validating the user input that becomes the name field. Or does that sound over engineered to you?

**Comment by gabrieljackson** [comment]
No, I was actually thinking the exact same thing about the name type! 0/5 on doing it or not, but I think that sounds great!

**Comment by jwilander** [comment]
Could this orphan any installations already created with capitals? Might need to lowercase the names pulled from the store when comparing to make sure that doesn't happen

**Comment by gigawhitlocks** [comment]
Yes I think so @jwilander -- I didn't consider external state. I'm going to refactor a bit to handle the repetition as well as the issue regarding orphaning installations.

**Comment by gigawhitlocks** [comment]
OK I have addressed @jwilander 's concern about orphaning old installations. I also went ahead and swapped everything to use a helper method like @gabrieljackson suggested. I did not do anything fancier than that -- I couldn't find a solution that was as clean as just using a helper method. Sometimes the straightforward approach is the right one.

Anyway, comments are addressed at this time.

**Pull request merged**
