### PR TITLE
[MM-45035] Updated http client to use mattermost-redux

### PR DESCRIPTION
**Pull request by fmartingr**
#### Summary

Updated HTTP client to use mattermost-redux's Client4 to avoid having CSRF errors in the future.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-45035

#### Release Note

```release-note
Updated HTTP Client to use mattermost-redux
```

### CODE REVIEW

**Review by gabrieljackson — APPROVED** [review]
LGTM! Just checking: did you run this locally just to check that the basics of the webUI seemed okay?

**Review by cpoile — APPROVED** [review]
Looks good, thank you @fmartingr! Echoing Gabe, let's make sure to do a full smoke-test this before merging. :)

**Comment by fmartingr** [comment]
> LGTM! Just checking: did you run this locally just to check that the basics of the webUI seemed okay?

> Looks good, thank you @fmartingr! Echoing Gabe, let's make sure to do a full smoke-test this before merging. :)

Yeah, I made some tests locally, created and deleted an instance just fine while checking that my profile popup displayed the list without console errors.

**Comment by cpoile** [comment]
@gabrieljackson Up to you then -- unless you want to get QA involved (if they have the bandwidth).

**Pull request merged**
