### PR TITLE
Enable autocomplete

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Enable autocomplete to allow users to discover this command easier

#### Ticket Link
https://community-daily.mattermost.com/core/pl/wn7tks4ctifidkyfhffr3qf7ae

#### Release Note
```release-note
Enable autocomplete
```

### CODE REVIEW

**Review by gabrieljackson — APPROVED** [review]
I know we left this disabled originally as the cloud plugin only works for Mattermost employees, but I am fine with enabling it if Joram wants to.

Another option is adding it as a config option for the plugin so it can be enabled or disabled by an admin.

**Comment by hanzei** [comment]
Well, if we add a config option that would still raise the question if it should be enabled for community or not.

**Comment by jwilander** [comment]
I'd like to leave it disabled unless it's causing major pain. We already get enough traffic and requests in our test account and advertising this plugin more is just going to increase the amount of that we have to deal with. In the future when we have more bandwidth to focus on it I'd be more inclined to turn on autocomplete for it.

**Comment by hanzei** [comment]
My main reason to enable it is discoverability. I didn't realized that a `/cloud` command exists until someone pointed it out to me. Enabling auto complete would make it easier for staff member to discover this feature. People need test accounts anyway. Streamlining the way they get them, might reduce the work because of a lower communication overhead.

**Comment by hanzei** [comment]
Closing per the above comment

**Pull request closed without merging**
